<a href="https://colab.research.google.com/github/aashrith123/TensorFlowCertificationUdemy/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook we are going to cover most funadmentals of tensors using tensor flow

We are going to cover
* Introducion to tensors
* Manipulating tensors
* Tensors and numpy
* Using @tf.function

## Introducation to tensors

In [ ]:
# Import Tensor flow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [ ]:
# Create tensors with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Checking number of dimensions of a tensor 
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
# Checking the dimension of vector
vector.ndim

1

In [ ]:
# Create a matrix

matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10., 3.],
                              [2., 6.],
                              [9., 11.]], dtype=tf.float16)  # specify data type is usind dtype paramater
                      
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  3.],
       [ 2.,  6.],
       [ 9., 11.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[16, 17, 18],
                       [19, 20, 21]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[16, 17, 18],
        [19, 20, 21]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6],
                       [33, 44, 55]],
                      [[7, 8, 9],
                       [10, 11, 12],
                       [100, 77, 88]],
                      [[16, 17, 18],
                       [19, 20, 21],
                       [44, 55, 11]]])
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[  1,   2,   3],
        [  4,   5,   6],
        [ 33,  44,  55]],

       [[  7,   8,   9],
        [ 10,  11,  12],
        [100,  77,  88]],

       [[ 16,  17,  18],
        [ 19,  20,  21],
        [ 44,  55,  11]]], dtype=int32)>

What we've created so far
* Scalar is single number
* Vector is a number with direction
* Matrix is a 2-dimensional array of numbers
* Tensor is a n-dimensional array of numbers

### Creating tesnors with 'tf.variable'

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try to change elements in changeable_tensor
changeable_tensor[0] = 7

TypeError: ignored

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try for uncgangeable_tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random tensors

In [ ]:
# Creating two randaom (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 4))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 4))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
       dtype=float32)>, <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
       dtype=float32)>, <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])>)

### .uniform will return random values based on uniform distribution
###### Link : https://mathworld.wolfram.com/UniformDistribution.html
### .random will return random values based on random distribution
### What is seed?
#### Seed in machine learning means the initialization state of a pseudo-random number generator. If you use the same seed you will get exactly the same pattern of numbers


### Shuffle the order of elements in a tensor